% clear all;clc;close all;
h = 5;
x = 6.75;
y = 0;
d_los = norm([x,y]);
d_mpc = norm([x, h + h - y]);
diff_d_mpc = d_mpc - d_los;
diff_index_mpc = diff_d_mpc/0.3;
index_mpc = diff_index_mpc +8;
phi_mpc = atan2(h+h-y, x);
phi_index_mpc = (phi_mpc + pi)/0.01;
phi_los = atan2(y,x);